---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/herostri/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp import.js $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH

    - /bin/cp -R sprites $DEPLOYPATH
    - /bin/cp -R input $DEPLOYPATH
    - /bin/cp -R game_objects $DEPLOYPATH
    - /bin/cp -R game_map $DEPLOYPATH
    - /bin/cp -R game_configs $DEPLOYPATH
    - /bin/cp -R game $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp -R textures $DEPLOYPATH
